version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linart_web
    restart: always
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/linart
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST:-true}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - linart_net

  db:
    image: postgres:15-alpine
    container_name: linart_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linart
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - linart_net

volumes:
  db_data:

networks:
  linart_net:
    driver: bridge
